# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blue Mountain Springs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Project page for Blue Mountain Springs, a project sponsored by the Center for
  Digital Humanities at Princeton University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
